volumes:
  db_storage:
  n8n_storage:

services:
  postgres:
    container_name: n8n_pg
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=abc
      - POSTGRES_PASSWORD=yourpass
      - POSTGRES_DB=n8n
      - POSTGRES_NON_ROOT_USER=abc
      - POSTGRES_NON_ROOT_PASSWORD=yourpass
    volumes:
      - db_storage:/var/lib/postgresql/data
      - /home/shrishesha/servar-config/n8n/pg/init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U abc -d n8n']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n:latest
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=abc
      - DB_POSTGRESDB_PASSWORD=yourpass
      - WEBHOOK_URL=https://your-url.com
      - WEBHOOK_TUNNEL_URL=https://your-url.com
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      - N8N_SECURE_COOKIE=false
    ports:
      - 5678:5678
    links:
      - postgres
    volumes:
      - n8n_storage:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy
