services:

  speedtest:
    restart: unless-stopped
    container_name: openspeedtest
    ports:
        - '3030:3000'
        - '3031:3001'
    image: openspeedtest/latest
  
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TUNNEL_TOKEN} # remember to replace your token here
    restart: unless-stopped
