services:
  qbittorrent:
      image: lscr.io/linuxserver/qbittorrent:latest
      container_name: qbittorrent
      restart: unless-stopped
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Asia/Kolkata
        - WEBUI_PORT=8080
      volumes:
        - /home/shrishesha/servar-config/downloaders/qbittorrent:/config
        - /home/shrishesha/downloads:/downloads
        - /servarr/Media:/media
      ports:
        - "8080:8080"
  metubedl:
    container_name: metube
    image: alexta69/metube:latest
    environment:
      - DARK_MODE=true
      - GID=1000
      - UID=1000
    ports:
      - 8081:8081
    restart: unless-stopped
    volumes:
      - /home/shrishesha/metube:/downloads
    privileged: false

  qui:
    image: ghcr.io/autobrr/qui:latest
    container_name: qui
    restart: unless-stopped
    ports:
      - "7476:7476"
    volumes:
      - /home/shrishesha/servar-config/downloaders/qui:/config